name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v4
      - name: Run PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff